1단계 미션 제출합니다
next-step/jwp-was-kakao pull request #10
Opened 2024-04-09 08:12 UTC by Eungu-Kwon

2024-04-10 02:51 UTC, seokhong requested changes
은구님, 1단계 미션 잘 구현하셨습니다. 👍
전체적으로 기능 잘 동작하고 테스트 성공하는 것 확인했습니다.
코멘트 확인 부탁드립니다. 🙂

2024-04-10 02:51 UTC, seokhong commented on src/main/java/utils/IOUtils.java
`HttpRequestTestHeader` 테스트가 실패하는 것으로 보이네요. 테스트가 성공할 수 있도록 구현 코드를 조금 수정해 보시면 좋겠습니다. :)

2024-04-10 02:51 UTC, seokhong commented on src/main/java/utils/IOUtils.java
> +    public static String readRequestLine(BufferedReader reader) throws IOException {
`readRequestLine`, `readHeader`는 특정한 조건 하에서만 의도한대로 동작할 것으로 보입니다.
이 기능은 `RequestHandler`에 구현해보면 어떨까요? `IOUtils`는 범용적인 기능을 가지는 유틸리티 클래스로 보이는데, 이 두 메서드는 정확히 첫 줄 혹은 헤더가 시작되는 줄에 호출되어야 의도한대로 동작할 것으로 보이네요.

2024-04-10 02:51 UTC, seokhong commented on src/main/java/webserver/GetRequestHandler.java
> +        if (httpRequest.getPath().equals("/user/create")) {
사용자를 생성하는 기능은 `PostRequestHandler`로 변경했으니, 이 코드는 제거해보면 어떨까요?

2024-04-10 02:51 UTC, seokhong commented on src/main/java/webserver/HttpResponse.java
> +    public void sendResponse(OutputStream out)
`HttpResponse`는 응답을 담는 객체로 보이네요. 현재와 같은 구조에서는 응답을 전달하기 위해, 모든 핸들러에서 `OutputStream`을 전달 받아서 `HttpResponse`에게 전달해줘야 할 것으로 보입니다.
각 핸들러에서는 `HttpResponse`를 만들고, 클라이언트에게 전달하는 것은 `RequestHandler`에서 해보면 어떨까요?

2024-04-10 02:51 UTC, seokhong commented on src/main/java/webserver/HttpResponse.java
> +        DataOutputStream dos = new DataOutputStream(out);
`DataOutputStream`도 close 가 필요한 자원으로 보이는데, try-with-resources 로 사용하지 않으신 이유가 있을까요? :)

2024-04-10 02:51 UTC, seokhong commented on src/main/java/webserver/PostRequestHandler.java
> +            HttpResponse httpResponse = new HttpResponse("302", "Found",
302, 404 등은 상태를 나타내는 HTTP status code 일텐데요. 상태 메시지와 코드를 별도의 객체로 관리해서, 무슨 상태가 있는지 볼 수 있도록 하고, 오타 등의 실수도 방지해보면 어떨까요?

2024-04-10 02:51 UTC, seokhong commented on src/main/java/webserver/RequestHandler.java
> +                Map.of("Content-Type", contentType != null ? contentType : "null"),
의미를 갖는 문자열은 enum, 상수 등을 적절하게 활용해 보시면 좋겠습니다.

2024-04-10 02:51 UTC, seokhong commented on src/main/java/webserver/HttpRequest.java
> +            String[] keyValue = token.split("=");
`=`가 우리가 기대한 형식과 다르게 들어오면 어떻게 될까요?
예를 들면, `params=a=b`와 같이요.

2024-04-10 02:51 UTC, seokhong commented on src/main/java/webserver/RequestHandler.java
> +            if (httpRequest.isMethod("GET") && responseResources(httpRequest.getPath(), out)) {
정적 리소스에 대한 처리도 `GET` 요청에 대한 처리이니 분리할 수 있지 않을까요?

2024-04-10 02:51 UTC, seokhong commented on src/main/java/webserver/RequestHandler.java
> +            if (httpRequest.isMethod("GET") && responseResources(httpRequest.getPath(), out)) {
현재 구현에서는 http method 가 늘어날 때마다 분기가 늘어날 것으로 보이는데요. 개선할 수 있는 방법을 고민해보면 어떨까요?

2024-04-11 07:37 UTC, Eungu-Kwon commented on src/main/java/webserver/HttpRequest.java
> +            String[] keyValue = token.split("=");
안녕하세요!
제가 테스트 해보았을 때는 구분자로 쓰이는 = 외에는 %3D로 인코딩 되어서 저장되는 것을 확인했습니다.
혹시 =이나 다른 구분자를 따로 처리하는 로직이 필요한지 궁금합니다!

2024-04-11 09:55 UTC, seokhong requested changes
은구님, 1단계 미션 코멘트 잘 반영하셨습니다. 👍 
어제 제가 코멘트에 은구님 이름을 잘못 작성하는 실수를 했네요. 죄송합니다. 🙇 
조금 더 고민해보시면 좋을 것 같은 내용이 있어 코멘트 추가로 남겼습니다. 확인 부탁드립니다. 🙂

2024-04-11 09:55 UTC, seokhong commented on src/main/java/webserver/HttpRequest.java
> +            String[] keyValue = token.split("=");
서버를 띄워서 테스트했을 때, 의도와 다르게 파라메터가 처리되는 것으로 보이네요!
<img width="1376" alt="스크린샷 2024-04-11 오후 6 36 34" src="https://github.com/next-step/jwp-was-kakao/assets/6284253/f75e03b7-12ac-4fc4-952e-267288d0ea30">
<img width="279" alt="스크린샷 2024-04-11 오후 6 37 00" src="https://github.com/next-step/jwp-was-kakao/assets/6284253/e735b525-afa5-4766-acc4-98c881fc7f68">

2024-04-11 09:55 UTC, seokhong commented on src/main/java/webserver/RequestHandler.java
> +            HttpResponse http404Response = new HttpResponse(HttpStatus.NOT_FOUND, null, null);
이 값은 handler를 찾지 못했을 때만 필요한 것으로 보이네요.
별도의 메서드로 분리해서 `orElse` 메서드에서 호출해보면 어떨까요? 코드를 읽을 때 중간에 404 응답을 왜 만드는지 궁금한 순간이 있었네요!

2024-04-11 09:55 UTC, seokhong commented on src/main/java/webserver/RequestHandler.java
> +            Map<String, MethodRequestHandler> handlers = new HashMap<>();
핸들러 맵, 핸들러는 서버가 뜬 이후에 변경되지 않을 값으로 보이네요.
필드 등으로 미리 만들어 놓고 재사용해보면 어떨까요?

2024-04-11 09:55 UTC, seokhong commented on src/main/java/webserver/http/HttpStatus.java
> +}
파일 마지막에 newline 이 없다고 깃헙에서 경고를 띄워주네요.  
파일 마지막의 newline 은 무슨 역할을 하는지 학습해보신 후, IDE 설정을 통해 휴먼 에러를 방지해보시면 좋겠습니다.

2024-04-11 09:55 UTC, seokhong commented on src/main/java/webserver/MethodRequestHandler.java
> +	Optional<HttpResponse> handler(HttpRequest httpRequest) throws IOException;
메서드의 이름은 `handle` 이 더 적절할 것으로 보이네요!

2024-04-11 09:55 UTC, seokhong commented on src/main/java/webserver/HttpResponse.java
> +    public void sendResponse(OutputStream out)
`HttpResponse` 에게 `OutputStream`을 전달하지 말고, `RequestHandler`에서 `DataOutputStream`을 생성해서 `HttpResponse`를 write 해보면 어떨까요?
`HttpResponse`는 응답 값을 가지고 있는 객체이고, `OutputStream`은 값을 출력하는 장치입니다. 현재의 코드는 마치 `종이`에게 `프린터`를 전달해서 출력하라고 시키는 것처럼 보이는 것 같은데, 어떻게 생각하시나요?

2024-04-12 12:06 UTC, seokhong approved these changes
은구님, 1단계 미션 코멘트 잘 반영하셨습니다. 👍 
1단계 PR 머지하겠습니다.
추가로 코멘트 남긴 내용은 2단계 미션을 진행하시며 참고해 보시면 좋겠습니다.
2단계 미션에서 뵙겠습니다. 🙂

2024-04-12 12:06 UTC, seokhong commented on src/test/java/webserver/HttpRequestTest.java
> +    void request_resttemplate2() {
위의 `request_resttemplate`과 동일한 테스트 코드로 보이네요. 중복되는 코드는 제거하면 어떨까요?

2024-04-12 12:06 UTC, seokhong commented on src/main/java/webserver/HttpRequest.java
> +public class HttpRequest {
`HttpRequest`의 구성 요소인 메서드, 경로, 헤더 등을 감싸는 객체를 만들어 보는 건 어떨까요?
[http message 형식](https://developer.mozilla.org/en-US/docs/Web/HTTP/Messages)을 보면 request line, headers, body 와 같이 명확한 이름과 형식이 정의되어 있으니, 클래스로 구현하면 가독성이 더 좋아질 것 같아요!

2024-04-12 12:06 UTC, seokhong commented on src/main/java/webserver/HttpRequest.java
> +    private Map<String, String> parseKeyValuePairs(String input, String delimiter) {
`delimiter`는 항상 `&`가 들어오니, 이 값을 상수로 정의하고 사용해도 괜찮지 않을까요?

2024-04-12 12:06 UTC, seokhong commented on src/main/java/webserver/HttpRequest.java
> +            Optional.of(keyValue)
`Optional`로 감싸고 filter, ifPresent를 활용하는 방법도 괜찮지만, 때로는 if 문을 이용하는 코드가 더 간결하고 가독성이 좋기도 합니다.
`keyValue`는 절대 null이 될 수 없는 값으로 보이는데, 코드를 읽는 사람에게는 어떤 변수를 `Optional`로 감싸는 순간 null 이 될 수도 있다는 의미로 전달될 수도 있어 보입니다.

2024-04-12 12:06 UTC, seokhong commented on src/main/java/webserver/http/HttpMethods.java
> +public class HttpMethods {
문자열 상수로 관리하는 것과 enum 으로 관리하는 것에도 차이가 있을 것 같아요.
문자열 상수와 enum의 장단점 등을 고민해보셔도 좋겠습니다. :)

2024-04-12 12:06 UTC, seokhong commented on src/main/java/webserver/http/HttpHeaders.java
> +package webserver.http;
http 패키지는 마치 상수만 정의하기 위한 패키지처럼 보이기도 하네요.
webserver 패키지의 일부가 http 스펙이라면 http 패키지로 옮기는 것이 적절하지는 않을까요?
반대로 webserver 에서 사용하는 상수를 http 패키지에 정의한 것이라면, 이 두 패키지는 결합도가 강하니 한 패키지로 관리하거나, http 패키지가 webserver 에서 사용하는 상수임을 나타내는 패키지로 변경하는게 가독성이 더 좋지 않을까 싶기도 합니다. :)

2024-04-12 12:06 UTC, merged