[1단계 - HTTP 웹 서버 구현] dino.shin(신종화) 미션 제출합니다.
next-step/jwp-was-kakao pull request #11
Opened 2024-04-09 08:23 UTC by jjongwa

안녕하세요! 이번 카카오 기술 온보딩 진행중인 디노라고 합니다! 🦖

이번 미션은 우선 한정된 시간 내에 최대한 객체지향 생활체조를 지키며 기능 요구사항을 완성하는 것을 목표로 두었습니다.

아직 고칠 부분도 많이 보이고, 조금 더 객체를 분리해 책임을 나누고 싶었지만
리뷰를 먼저 받고 해당 사항과 같이 리팩토링을 진행하면 좋을 것 같아 우선 이렇게 요청 보냅니다!

이번 미션 잘 부탁드립니다!🙇🙇🙇

2024-04-10 02:48 UTC, sah3122 requested changes
안녕하세요 WAS 미션 리뷰를 맡은 이동철 입니다. 
첫번째 미션 구현 잘해주셨습니다 👍 
몇가지 코멘트 남겨두었는데 확인 부탁드려요 !

2024-04-10 02:48 UTC, sah3122 commented on src/main/java/webserver/CustomHttpExtension.java
> +public enum CustomHttpExtension {
WebServer를 구현하는 입장으로 `Custom`이란 prefix 를 제거해보는건 어떨까요 ?

2024-04-10 02:48 UTC, sah3122 commented on src/main/java/webserver/CustomHttpExtension.java
> +    ICO(".ico", "image/svg+xml", "templates"),;
확장자 정의잘해주셨습니다 👍

2024-04-10 02:48 UTC, sah3122 commented on src/main/java/webserver/RequestHandler.java
>  public class RequestHandler implements Runnable {
RequestHandler 구현 잘해주셨습니다 👍

2024-04-10 02:48 UTC, sah3122 commented on src/main/java/webserver/RequestHandler.java
> +            if (customRequest.isMethodEqual(CustomMethod.POST) && isCreateUserRequest(customRequest)) {
HTTP 메서드 & Request URL가 추가됨에 따라 조건문이 추가되어야 하는 구조입니다. 
조건문의 추가 없이 요청을 처리할수 있도록 정의해보는건 어떨까요 ?

2024-04-10 02:48 UTC, sah3122 commented on src/main/java/webserver/RequestHandler.java
> +    }
HttpRequest 객체를 정의한것과 동일하게 HttpResponse 객체를 관리해보는것도 좋은 경험이 될것 같습니다 😄

2024-04-10 02:48 UTC, sah3122 commented on src/main/java/webserver/RequestHandler.java
> +    private boolean createUser(final CustomRequest customRequest) {
RequestHandler 클래스가 비즈니스 로직까지 수행하는것은 너무 많은 책임을 가지고 있다고 생각해요.

2024-04-10 02:48 UTC, sah3122 commented on src/main/java/webserver/request/CustomBody.java
> +package webserver.request;
Http Request 구현 잘해주셨습니다 👍

2024-04-10 02:48 UTC, sah3122 commented on src/main/java/webserver/request/CustomBody.java
> +        this.elements = QueryStringParser.parse(body);
RequestBody에서 QueryStringParser만 사용가능하지는 않을것 같아요 😄 
Body에서 파싱가능한 ContentType 을 관리 해보는건 어떨까요 ?

2024-04-10 02:48 UTC, sah3122 commented on src/main/java/webserver/request/CustomPath.java
> +public class CustomPath {
Path를 조금더 세분화하여 관리해볼수 있을것 같아요 😄

2024-04-10 02:48 UTC, sah3122 commented on src/main/java/webserver/request/CustomRequest.java
> +public class CustomRequest {
Request 객체 구현 잘해주셨네요 👍

2024-04-11 14:50 UTC, jjongwa commented on src/main/java/webserver/CustomHttpExtension.java
> +public enum CustomHttpExtension {
spring 의존성이 추가되어 있어 구분을 주고자 이번 미션에서 새로 구현하는 클래스들에 대해서 custom을 주었는데, 
그냥 auto Import 설정을 끄고 custom prefix를 모두 제거하는 방식으로 변경했습니다.!  https://github.com/next-step/jwp-was-kakao/pull/11/commits/675893fa0e1b52b1206673effa5af93d6e05541b

2024-04-11 14:53 UTC, jjongwa commented on src/main/java/webserver/RequestHandler.java
> +    private boolean createUser(final CustomRequest customRequest) {
controller가 없는 상황에서 이미 중복된 유저가 있는지 확인하는 로직은 Handler가 담당하는게 아직까지는 알맞다고 생각했습니다.!
하지만, createUser라는 네이밍이 오해의 소지가 있다고 생각이 변경 진행했습니다!

2024-04-11 14:59 UTC, jjongwa commented on src/main/java/webserver/request/CustomBody.java
> +        this.elements = QueryStringParser.parse(body);
request header에서 content type을 확인한 후 이에 맞게 RequestBody를 생성하는 방식으로 이해하면 될까요?

2024-04-11 15:00 UTC, jjongwa commented on src/main/java/webserver/RequestHandler.java
> +    }
이 부분도 우선 1단계에선 제공된 response 메서드를 최대한 활용하는 방식으로 진행하고 싶었습니다!
response 부분에 대한 객체 분리는 3단계에서 진행해도 괜찮을까요..!

2024-04-11 15:02 UTC, jjongwa commented on src/main/java/webserver/RequestHandler.java
> +            if (customRequest.isMethodEqual(CustomMethod.POST) && isCreateUserRequest(customRequest)) {
아직은 요구사항에서 두 가지 상황밖에 주어지지 않아 Controller를 통한 추상화는 과도한 구현이라고 생각했습니다.
해당 부분은 3단계에서 본격적으로 진행해보려 합니다!

2024-04-11 15:03 UTC, jjongwa commented on src/main/java/webserver/request/CustomPath.java
> +public class CustomPath {
path 부분을 resource와 paramter로 나누어 보았습니다.! https://github.com/next-step/jwp-was-kakao/pull/11/commits/b57313bd393048796c52e0e50e9abb5284125283

2024-04-11 15:18 UTC, jjongwa commented
@sah3122 리뷰 반영이 조금 늦었습니다..🙇

Controller 생성과 response 객체 분리 부분은 반영하지 않았는데요, 
먼저, 해당 부분은 현재 진행중인 1단계의 구현 범위에서는 요구되는 사항이 아니라고 생각했고, 
단계적으로 진행하지 않고 처음부터 모든 분리와 추상화를 진행하면, 이미 존재하는 톰캣 Coyote구조를 보고 베끼는 것과 다를게 없다는 생각이 들었습니다. (물론, 3&4단계는 선택 부분이라 미리 이런 리뷰를 주셨을 것 같긴 합니다..!)

그래서 남겨주신 해당 부분에 대한 리팩토링은 조금 미뤄뒀다 3단계에서 진행하고 싶습니다..!

리뷰어님이 생각하시기에 이번 스텝에서 꼭 리팩토링을 진행하고 2단계로 넘어가야 할 부분이 있거나, 
제가 생각하지 못한 다른 의도가 있으셨다면 다시 RC 부탁드립니다!!🙇🙇

2024-04-12 05:58 UTC, sah3122 commented on src/main/java/webserver/RequestHandler.java
> +            if (customRequest.isMethodEqual(CustomMethod.POST) && isCreateUserRequest(customRequest)) {
3단계 미션의 요구사항을 제가 놓치고 있었습니다 🙏 
이야기 주신것처럼 3단계에서 진행하는것도 좋을것 같아요 😄

2024-04-12 06:03 UTC, sah3122 commented on src/main/java/webserver/request/CustomBody.java
> +        this.elements = QueryStringParser.parse(body);
네 맞습니다 ~!

2024-04-12 06:10 UTC, sah3122 commented
@jjongwa 님 안녕하세요 😄 
앞선 코멘트와 같이 3단계 미션을 진행하고자 하신다면 남겨드린 코멘트는 추후 리팩토링 미션에서 진행해주시면 될것 같습니다. 
이번 미션에서의 요구사항은 너무 잘 구현해주셨기 때문에 다음 미션으로 넘어가도록 할게요 👍

2024-04-12 06:10 UTC, sah3122 approved these changes
피드백 반영 잘해주셨습니다 👍 
질문에 대한 답변 남겨두었는데 확인 부탁드리며 다음 미션도 화이팅하세요 !

2024-04-12 06:11 UTC, merged