1단계 미션 제출합니다.
next-step/jwp-was-kakao pull request #27
Opened 2024-04-15 02:40 UTC by ddingmin

안녕하세요.

1단계 미션을 완료해서 제출합니다.

mvc 패턴을 적용해보았는데, 아직 view에 대한 처리는 분리하지 못했습니다.

다음 미션에서 분리하며 진행해보려 합니다. 감사합니다!

2024-04-15 10:33 UTC, seokhong requested changes
성민님 안녕하세요! 웹 서버 구현 미션을 함께 할 리뷰어 김석홍입니다. 만나서 반갑습니다!
1단계 미션 잘 구현하셨습니다. 👍
전체적으로 기능 동작하고 테스트 성공하는 지 확인하고, 코멘트 남겼습니다.
코멘트 확인 부탁드립니다. 🙂

2024-04-15 10:33 UTC, seokhong commented on src/test/java/webserver/http/HttpRequestTest.java
> +    void request_resttemplate() {
이 테스트가 실패하는 것으로 보이네요. 성공할 수 있도록 프로덕션 코드 구현을 수정해 보시면 좋겠습니다. :)

2024-04-15 10:33 UTC, seokhong commented on src/main/java/utils/KeyValueParser.java
> +            return Arrays.stream(input.split("&"))
파싱을 위해 의미를 가지는 특수 문자는 상수로 분리해 보면 어떨까요?
또한, 이 파서는 query string 포맷에 한정한 파서로 보이는데, utils 패키지에 두는 것이 적절할까요? webserver 또는 http 에 의존하는 것 같기도 하니, 옮기는 게 필요하진 않을까요?

2024-04-15 10:33 UTC, seokhong commented on src/main/java/utils/KeyValueParser.java
> +                    .map(it -> it.split("="))
`=`가 우리가 기대한 형식과 다르게 들어오면 어떻게 될까요?
예를 들면, `params=a=b`와 같이요.

2024-04-15 10:33 UTC, seokhong commented on src/main/java/webserver/RequestHandler.java
> +            httpRequest.setBody(RequestReaderUtils.readBody(reader, Integer.parseInt(httpRequest.getAttribute("Content-Length"))));
`HttpRequest`를 생성한 순간부터 body 값이 유의미한 값을 가지도록, `setBody` 를 호출하는 대신 생성자에서 body 도 전달받아서 객체를 생성하면 어떨까요?

2024-04-15 10:33 UTC, seokhong commented on src/main/java/webserver/RequestHandler.java
> +            handler.handling(httpRequest, httpResponse);
`httpResponse`를 생성해서 전달하지 말고, `handler`가 `httpRequest`를 처리한 후 `httpResponse`를 직접 만들어서 반환해주면 어떨까요?

2024-04-15 10:33 UTC, seokhong commented on src/main/java/webserver/RequestHandler.java
> +    private void response200Header(DataOutputStream dos, int lengthOfBodyContent) {
이 메서드는 사용하는 곳이 없으니 제거하시면 좋겠습니다.

2024-04-15 10:33 UTC, seokhong commented on src/main/java/webserver/controller/Controller.java
> +public interface Controller {
특정 컨트롤러가 `doGet` 또는 `doPost` 중 하나만 제공한다면 인터페이스의 변경이 필요하진 않을까요?

2024-04-15 10:33 UTC, seokhong commented on src/main/java/webserver/controller/UserController.java
> +    public String register(UserRequest request) {
메서드의 배치는 어떤 순서로 하시나요? :)

2024-04-15 10:33 UTC, seokhong commented on src/main/java/webserver/controller/UserController.java
> +        if (request.getPath().equals("/user/create")) {
사용자를 생성한 후 index.html 페이지로 리다이렉트가 안 되는 것으로 보이네요!

2024-04-15 10:33 UTC, seokhong commented on src/main/java/webserver/controller/UserController.java
> +        if (request.getPath().equals("/user/create")) {
POST 요청으로 변경하는 것이 요구사항이니, GET 요청 처리는 제거하면 어떨까요?

2024-04-15 10:33 UTC, seokhong commented on src/main/java/webserver/handler/Handler.java
> +    void handling(HttpRequest httpRequest, HttpResponse httpResponse);
`handling` 대신 `handle` 로 변경하면 어떨까요?

2024-04-15 10:33 UTC, seokhong commented on src/main/java/webserver/http/Extension.java
> +        return Arrays.stream(Extension.values())
매번 배열을 순차적으로 돌며 값을 찾는 것보다, 맵을 활용하는 것이 시간 복잡도 측면에서 유리하진 않을까요?

2024-04-15 10:33 UTC, seokhong commented on src/main/java/webserver/http/Headers.java
> +        this.headers.put("Content-Length", "0");
`Content-Length` 헤더를 사용하지 않는 경우도 있을 것 같은데, 생성자에서 기본 값을 넣어주는 게 적절할까요?

2024-04-15 10:33 UTC, seokhong commented on src/main/java/webserver/http/Headers.java
> +    private Map<String, String> headers = new HashMap<>();
헤더의 키 값도 enum 으로 관리할 수 있진 않을까요?

2024-04-15 10:33 UTC, seokhong commented on src/main/java/webserver/http/HttpResponse.java
> +        return "HTTP/1.1 " + statusCode.getValue() + " " + statusCode.getMessage();
http 버전이 달라질 때 `getStartLine` 구현을 변경해야 한다는 것을 기억하기 어렵진 않을까요?
protocol version 과 같은 클래스 또는 enum 을 이용해보는 건 어떨까요?

2024-04-15 10:33 UTC, seokhong commented on src/main/java/webserver/http/HttpStatus.java
> +public enum HttpStatus {
응답 코드, MIME에 대한 관리 좋습니다. 👍

2024-04-15 10:33 UTC, seokhong commented on src/main/java/webserver/http/StartLine.java
> +public class StartLine {
request 의 시작 줄은 `RequestLine`, response 의 시작 줄은 `StatusLine` 이라고 불린다고 하네요. :)

2024-04-15 10:33 UTC, seokhong commented on src/main/java/webserver/http/StartLine.java
> +    private void initAttributes(String queryString) {
`KeyValueParser`와 중복되는 코드로 보이는데, 중복을 제거할 수 있지 않을까요?

2024-04-17 01:38 UTC, ddingmin reviewed
먼저 리뷰 감사합니다!
Controller와 HttpMethod에 따라 처리해주는 부분을 어떤 방식으로 구현해야하는지 어렵더라구요.
이 부분에 집중해서 의견 주시면 감사하겠습니다! 🙏

2024-04-17 01:38 UTC, ddingmin commented on src/main/java/webserver/http/HttpResponse.java
> +        return "HTTP/1.1 " + statusCode.getValue() + " " + statusCode.getMessage();
enum 클래스 추가해서 관리하도록 수정했습니다!

2024-04-17 01:38 UTC, ddingmin commented on src/main/java/utils/KeyValueParser.java
> +                    .map(it -> it.split("="))
`params=a=b`같은 경우에는 key 값으로 `params`, value 값으로`a=b`와 같은 값을 받아내도록 변경했습니다!

첫 `=`을 기준으로 잘라내었습니다!

2024-04-17 01:38 UTC, ddingmin commented on src/main/java/webserver/RequestHandler.java
> +            httpRequest.setBody(RequestReaderUtils.readBody(reader, Integer.parseInt(httpRequest.getAttribute("Content-Length"))));
사용자의 요청에 대해 ReqeustLine, Headers, Body에 대해 큰 분류는 HttpRequestParser에게 역할을 맡겨, 생성자에서 모든 필드값을 가지도록 수정했습니다!

2024-04-17 01:38 UTC, ddingmin commented on src/main/java/webserver/http/Headers.java
> +    private Map<String, String> headers = new HashMap<>();
헤더의 값을 enum으로 관리하게 된다면, 특수한 key값을 가진 경우에는 값을 담아내기 어렵다고 생각했습니다.

자주 사용하는 값들 같은 경우에는 관리할 수 있지만 유동적으로 관리하기 힘들기 때문에 자주 사용하는 값만 상수로 관리하는 방법은 어떻게 생각하시는지 궁금합니다!

2024-04-17 01:38 UTC, ddingmin commented on src/main/java/webserver/http/Extension.java
> +        return Arrays.stream(Extension.values())
미리 맵을 활용한다면 시간적 측면에서는 유리하지만, 메모리적 측면에서는 순회를 도는게 유리하다고 생각하는데 어떤게 정답인지는 감이 오지 않는데 리뷰어님의 생각도 궁금합니다!

2024-04-17 01:38 UTC, ddingmin commented on src/main/java/webserver/controller/UserController.java
> +    public String register(UserRequest request) {
생성자를 가장 위에 두는 편이고, public 메서드들을 위로 위치시킵니다.

Controller 같은 경우에는 doGet, doPost와 같은 부분은 역할이 조금 다른 경향이 있어 밑으로 배치했습니다! (추후 클래스 분리가 필요해보이는데 아직 감이 안잡혀서요,,!)

2024-04-17 01:38 UTC, ddingmin commented on src/main/java/webserver/RequestHandler.java
> +            handler.handling(httpRequest, httpResponse);
처음에는 setter를 지양하려고, 석홍님 방법으로 고민했는데 구현하다보니 복잡해져서 일단은 직접 넘기는 방법으로 만들어주었습니다. 2단계 리팩토링에서 적용해보도록 할게요!

2024-04-17 01:38 UTC, ddingmin commented on src/main/java/webserver/controller/Controller.java
> +public interface Controller {
이 부분도 고민인데 리뷰어님의 생각이 궁금합니다..!!!!

2024-04-17 10:45 UTC, seokhong commented on src/main/java/webserver/controller/Controller.java
> +public interface Controller {
여러 구현 방법을 고민해보셨을 것 같아요! 각 방법의 장단점을 생각해보신 후, 이렇게 결정하신 이유도 말씀해주시면 서로 더 많은 이야기를 나눠볼 수 있을 것 같아요. :)

저는 `Map<String, Function<RequestEntity, ResponseEntity>>`, `Map<HttpMethod, Router>` 를 이용하여 http method 와 path 로 이를 처리하는 메서드를 찾는 형태를 생각해 봤습니다. 혹은 `Controller`가 하나의 메서드만 구현하도록 인터페이스를 만들고, `Function` 대신 `Controller`를 값으로 갖는 맵을 사용할 수도 있을 것 같아요.

2024-04-17 10:46 UTC, seokhong commented on src/main/java/webserver/controller/UserController.java
> +    public String register(UserRequest request) {
아직 클래스를 분리하지 않은 상태이니, 내부에서만 사용하는 register 메서드의 접근 제어자를 private 으로 변경하는 건 어떨까요?

2024-04-17 10:48 UTC, seokhong commented on src/main/java/webserver/http/Extension.java
> +        return Arrays.stream(Extension.values())
이 enum 을 저장하는데 메모리가 얼마나 필요할까요? 메모리의 사용량이 트레이드오프에서 고려해야 할만큼 클까요?
반면, 시간적으로는 이 메서드의 호출 횟수만큼 이점이 있을 것 같아요. 구현 후 랜덤하게 extension 을 전달하여 소요 시간을 비교해보면 어떨까요?

2024-04-17 10:50 UTC, seokhong commented on src/main/java/webserver/http/Headers.java
> +    private Map<String, String> headers = new HashMap<>();
합리적이라고 생각합니다. 👍

2024-04-17 10:52 UTC, seokhong approved these changes
성민님, 1단계 미션 코멘트 잘 반영하셨습니다. 👍 
1단계 PR 머지하겠습니다.
의견 남겨주신 내용에 대한 제 생각 코멘트로 남겼습니다. 2단계 미션 진행하실 때 참고 부탁드립니다.
2단계 미션에서 뵙겠습니다. 🙂

2024-04-17 10:52 UTC, merged