1단계 미션 제출합니다.
next-step/jwp-was-kakao pull request #3
Opened 2024-04-09 07:33 UTC by gunom

2024-04-09 14:40 UTC, liquidjoo requested changes
안녕하세요 건모님 :)
이번 미션 리뷰어를 맡은 김성주 입니다
1단계 구현 정말 잘해주셨어요 👍 
몇 가지 코멘트 남겼는데요~ 확인하고 다시 요청 주세요 🙇

2024-04-09 14:40 UTC, liquidjoo commented on src/main/java/model/User.java
> +    }
주 생성자가 있다면 this() 를 활용해 보아도 좋지 않을까요?

2024-04-09 14:40 UTC, liquidjoo commented on src/main/java/service/UserService.java
> +        User user = new User(requestParams);
requestParams 에서 원하는 값이 없다면 어떻게 될까요?

2024-04-09 14:40 UTC, liquidjoo commented on src/main/java/utils/FileIoUtils.java
> +    }
uriPath or 확장자에 따른 분기 처리를 추상화 해본다면 어떻게 진행해 볼 수 있을까요?

2024-04-09 14:40 UTC, liquidjoo commented on src/main/java/utils/ParseUtils.java
> +        return Collections.unmodifiableMap(paramsMap);
&가 여러개 있다거나, key, value 가 정상적이지 않을 때엔 어떻게 처리할 수 있을까요?

2024-04-09 14:40 UTC, liquidjoo commented on src/main/java/webserver/RequestHandler.java
> +            Response response = Controller.handle(request);
컨트롤러 활용 👍

2024-04-09 14:40 UTC, liquidjoo commented on src/main/java/webserver/request/Method.java
> +public class Method {
메소드를 매번 만드는 것도 좋지만 로또에서 배웠던 것 처럼 자주사용된다면 캐싱 처럼 사용해 보아도 좋을 것 같네요 :)

2024-04-09 14:40 UTC, liquidjoo commented on src/main/java/webserver/request/Path.java
> +        if (path.contains("?")) {
문자열은 상수화 해주면 더욱 의미있는 처리가 될 것 같아요 :)

2024-04-09 14:40 UTC, liquidjoo commented on src/main/java/webserver/response/FileResponse.java
> +        }
다중 if 를 제거해 보면 좋을 것 같아요 :)
> 추상화 설계를 해보면 좋을 것 같네요~

2024-04-09 14:40 UTC, liquidjoo commented on src/test/java/webserver/PathTest.java
> +        assertThat(params.get("job")).isEqualTo("programmer");
assertThat 도 좋지만 assertAll 도 활용해 보면 좋습니다 :)
assertThat , assertAll 은 어떤 차이가 있을까요?

2024-04-09 14:40 UTC, liquidjoo commented on src/main/java/webserver/request/Path.java
> +        return params;
```suggestion
        return new HashMap<>(params);
```
별건 아니지만 방어적 복사를 해주는 것도 의미가 있을 것 같네요 :)

2024-04-11 01:05 UTC, gunom commented on src/main/java/service/UserService.java
> +        User user = new User(requestParams);
validation 추가해보겠습니다!

2024-04-11 01:06 UTC, gunom commented on src/main/java/utils/ParseUtils.java
> +        return Collections.unmodifiableMap(paramsMap);
validation 추가해보겠습니다!

2024-04-11 01:06 UTC, gunom commented on src/main/java/webserver/request/Method.java
> +public class Method {
메소드는 그렇게 접근하는게 훨씬 좋겠네요!

2024-04-11 10:39 UTC, liquidjoo approved these changes
안녕하세요 건모님 :)
1단계 미션 피드백 잘해주셨어요 💯 
다음 단계 진행해 주세요 🙇

2024-04-11 10:39 UTC, liquidjoo commented on src/main/java/model/User.java
> +        this(requestParams.get("userId"), requestParams.get("password"), requestParams.get("name"), requestParams.get("email"));
피드백 반영 👍

2024-04-11 10:39 UTC, liquidjoo commented on src/main/java/utils/ContentTypeResolver.java
> +    }
static 영역 활용 👍 
메모리에 올려 재사용성에 대한 이점을 높일 수 있겠네요~

2024-04-11 10:39 UTC, liquidjoo commented on src/main/java/utils/FilePathConverter.java
> +    private static final String STATIC_DIRECTORY = "./static";
상수화 좋습니다 :)

2024-04-11 10:39 UTC, liquidjoo commented on src/main/java/webserver/request/Method.java
> +    }
피드백 반영 👍

2024-04-11 10:39 UTC, liquidjoo commented on src/main/java/webserver/response/FileResponse.java
> +        return ContentTypeResolver.getContentType(path);
다중 if 제거 좋습니다 :)
> 다중 if 를 사용해야할 때 어떻게 다른 방법으로 처리할 수 있을지 고민해보면 좋습니다

2024-04-11 10:39 UTC, merged