2단계 로그인 구현 미션 제출합니다.
next-step/jwp-was-kakao pull request #32
Opened 2024-04-16 02:14 UTC by BuchuKim

## 추가된 사항
- 세션 관리를 위한 `SessionManager`의 필드로 `Map<String, SessionEntity>`를 두어 JSESSIONID값을 key로 갖는 각 유저의 세션을 저장했습니다. 세션 id가 다른 다수의 유저를 동시에 저장할 수 있습니다.
- `SessionEntity`에 역시 각 세션의 정보를 담는 `Map<String, Object> sessionStorage` 필드를 두고 있습니다. 한 명의 사용자가 key로 구분되는 여러개의 세션 데이터를 가질 수 있습니다. 로그인은 사용자 로그인시 `user`키 값의 value에 `User`엔티티를 직접 저장하는 것으로 구현했습니다만..(값이 null일 경우 로그인이 안된 것) `password` 필드가 있음을 고려하여 보안을 위해 세션 저장용 VO를 따로 두는 것도 방법이라고 생각합니다.
- 쿠키 관리를 위해 내부에 key, value 필드를 갖는 `HttpCookie`를 추가했습니다. set cookie응답을 줄 때 `ResponseEntity#addCookie`메소드를 사용하고, 사용자 요청 쿠키 정보를 받을때 `RequestHeader#getCookie`를 사용했습니다.
- `ViewResolver`는 model을 받아 문자열로 구성된 동적 HTML을 반환하는 역할을 합니다.(일단 static으로 구성했습니다..) 기존의 `byte[]`를 인자로 받는`ResponseEntity`에 String으로 값을 초기화할 수 있는 `fromHtmlData()`메소드를 추가했습니다.

## 변경된 사항
- 컨트롤러들은 `Controller` 인터페이스를 구현하는 구현체들입니다. `ControllerMapper`라는 필드에 `Map<String, Controller>`로 보관되어 있습니다. 각 컨트롤러들은 자신들이 처리 가능한 엔드포인트인 `TARGET_PATH`라는 필드를 두고있고, 이것들을 key로 사용자가 각 controller의 서비스를 받을 수 있는 것입니다! (`ControllerMapper.java` 참고)

## 고민한 사항
- 문자열의 데이터를 요청/응답 객체로 변환할 때, 어디까지가 도메인의 영역이고 어디까지가 구현체의 영역인지 구분하기 애매했던 것 같습니다.
- HTTP 문자열 데이터를 응답/요청 객체로 변환하는 것은 상식적으로 봤을 때 비즈니스 로직의 영역은 아닌듯? 이라는 생각에 원래 xxParser로 끝나는 클래스들을 utils에 넣었는데요.
- 저는 이렇게 "비즈니스 로직"이 들어가지 않고 static으로 표현되는 것으로 충분한 객체는 컴포넌트로 두거나 진짜 스태틱 유틸 클래스로 놔둬왔던 것 같습니다(프로메테우스의 메트릭 데이터를 엔티티 객체로 파싱하는 등)
- 그치만 지금 상황은  지난 PR에 리뷰 주신 것처럼, 원래 utils에 두었던 여러 Parser들은 단순히 요청/응답 객체를 만드는 일만 할 뿐이므로 지금은 entity 안에 한꺼번에 옮겼습니다!

2024-04-16 13:25 UTC, seokhong requested changes
승희님, 2단계 미션 잘 구현하셨습니다. 👍 
코멘트로 구현하신 내용을 잘 설명해주셔서 코드를 읽고 이해하는데 도움이 많이 됐습니다.
기능 동작하는지 확인했고, 코멘트 남겨주신 내용에 대한 제 생각 포함하여 코드에 코멘트 남겼습니다.
코멘트 확인 부탁드립니다. 🙂

2024-04-16 13:25 UTC, seokhong commented on README.md
> +## 로그인 기능 목록
아래 기능이 구현되지 않은 것으로 보이네요!
- 로그인된 상태에서 `/user/login` 페이지에 HTTP GET method로 접근하면 이미 로그인한 상태니 `index.html` 페이지로 리다이렉트 처리한다.

2024-04-16 13:25 UTC, seokhong commented on src/main/java/controller/UserController.java
> +    private static final List<String> TARGET_PATHS = List.of("/user/list");
`http://localhost:8080/user/list.html`에 접근했을 때, 처리하는 부분에 버그가 있는 것으로 보이네요!
<img width="926" alt="스크린샷 2024-04-16 오후 9 51 15" src="https://github.com/next-step/jwp-was-kakao/assets/6284253/52e86757-be49-4ed6-8476-705cfd742cdc">

2024-04-16 13:25 UTC, seokhong commented on src/main/java/webserver/entity/HttpCookie.java
> +        return "Set-Cookie: " + toCookieString() + "; Path=/";
`Path` attribute 를 기본으로 "/"로 전달할 수도 있지만, 이 값도 변경될 수 있으니 속성으로 관리해봐도 좋을 것 같아요!
[문서](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies)를 참고하시면 몇 가지 속성이 나와 있네요. :)

2024-04-16 13:25 UTC, seokhong commented on src/main/java/webserver/WebApplicationServer.java
> +    private static ControllerMapper createControllerMapper() {
이전보다 어플리케이션과 WAS의 역할이 좀 더 분리된 것으로 보이네요!
현재 구조에서는 컨트롤러 내부에서 GET, POST 요청을 구분해서 처리하게 되는데요.
`ControllerMapper`를 계층적 구조로 만들면, GET/POST/PUT 등 HTTP method 에 따른 분기를 하고, 이후 path 에 대한 분기를 하는 형태로도 구현이 가능하지 않을까요?

2024-04-16 13:25 UTC, seokhong commented on src/main/java/controller/ControllerMapper.java
> +    private final Map<String, Controller> controllers;
컨트롤러를 밸류로 관리하는 방법도 있고, `Function<RequestEntity, ResponseEntity>`를 이용하여 메서드 참조를 밸류로 관리하는 방법도 있을 것 같아요.
각 방법의 장단점을 비교해 보시면 좋을 것 같고, `WebApplicationServer.java`에 남긴 코멘트도 함께 참고해 보시면 좋겠습니다.

2024-04-16 13:25 UTC, seokhong commented on src/main/java/webserver/entity/request/RequestHeader.java
> +        return HttpCookie.fromCookieString(headers.get("Cookie"))
`Cookie` 등 자주 사용되는 헤더를 상수로 관리해보면 어떨까요?

2024-04-16 13:25 UTC, seokhong commented on README.md
> 문자열의 데이터를 요청/응답 객체로 변환할 때, 어디까지가 도메인의 영역이고 어디까지가 구현체의 영역인지 구분하기 애매했던 것 같습니다.

도메인과 구현체의 구체적인 예시 클래스는 어떤 게 있을까요? 승희님과 용어를 맞춰서 이야기 해보면 도움이 될 것 같아서 여쭤봐요.

> HTTP 문자열 데이터를 응답/요청 객체로 변환하는 것은 상식적으로 봤을 때 비즈니스 로직의 영역은 아닌듯? 이라는 생각에 원래 xxParser로 끝나는 클래스들을 utils에 넣었는데요.
저는 이렇게 "비즈니스 로직"이 들어가지 않고 static으로 표현되는 것으로 충분한 객체는 컴포넌트로 두거나 진짜 스태틱 유틸 클래스로 놔둬왔던 것 같습니다(프로메테우스의 메트릭 데이터를 엔티티 객체로 파싱하는 등)
그치만 지금 상황은 지난 PR에 리뷰 주신 것처럼, 원래 utils에 두었던 여러 Parser들은 단순히 요청/응답 객체를 만드는 일만 할 뿐이므로 지금은 entity 안에 한꺼번에 옮겼습니다!

말씀하신 것과 동일하게, 저도 "비즈니스 로직"에 의존성이 없는 코드를 유틸리티로 관리하는 편입니다. 구체적으로 도메인에 대한 지식이 전혀 없는 코드(e.g., `StringUtils#isBlank`, `Executor#executeIfNotNull`, `BooleanUtils#isFalse`)로, 어느 도메인에서든 사용할 수 있는 공통 코드를 유틸리티로 관리합니다.

또한, "비즈니스 로직"이라는 것이 구현하는 서비스나 범위에 따라 다르게 생각될 수 있을 것 같아요. 저는 이번 미션 코드에 WAS와 어플리케이션 코드가 존재한다고 생각했고, WAS와 어플리케이션 각 컴포넌트에 도메인이 존재한다고 생각했습니다. 이러한 관점에서 WAS에도 도메인, 유틸리티가 있고, 어플리케이션에도 도메인, 유틸리티가 있을 수 있다고 생각했어요.

그래서 말씀하신 `xxParser`가 비즈니스 로직과 연관이 없는지에 대해 서로 다르게 생각한 것 같아요.
저는 WAS 구현을 봤을 때, `RequestEntity`, `ResponseEntity`는 도메인 코드이고, 이를 만들기 위한 클래스(`xxParser`)도 도메인에 대한 지식이 있으므로 도메인 패키지가 적절하다고 생각했습니다. 예를 들어, `RequestParser` 대신 `RequestFactory`, `RequestCreator`와 같은 이름이었다면 어떨까요? 특정한 객체를 생성하는 클래스라면 같은 패키지로 관리하게 되지 않을까요?

2024-04-17 01:18 UTC, BuchuKim commented on src/main/java/controller/UserController.java
> +    private static final List<String> TARGET_PATHS = List.of("/user/list");
`"/user/list"`엔드포인트로만 설정했군요. `UserController#TARGET_PATH` 리스트에 `/user/list.html`추가했습니다. 🫢

2024-04-17 06:13 UTC, BuchuKim commented on README.md
> +## 로그인 기능 목록
빼먹어버렸네요. `LoginController`에 관련 기능 추가했습니다.

2024-04-17 07:05 UTC, BuchuKim commented on src/main/java/webserver/entity/HttpCookie.java
> +        return "Set-Cookie: " + toCookieString() + "; Path=/";
재밌는 문서 감사합니다~~ `Path` 이외의 속성 역시 동적으로 추가할 수 있도록 아예 Map타입의 필드로 바꿔서 쿠키들을 저장할 수 있도록 구성해보았습니다. [커밋](https://github.com/next-step/jwp-was-kakao/pull/32/commits/41404ae63a91b40b4f9f2bc294fc8793cb71076c)

2024-04-17 07:07 UTC, BuchuKim commented on src/main/java/webserver/entity/request/RequestHeader.java
> +        return HttpCookie.fromCookieString(headers.get("Cookie"))
`RequestHeader.COOKIE_KEY`, `HttpCookie.JSESSIONID_KEY`등을 상수로 빼보았습니다.

2024-04-17 08:39 UTC, BuchuKim commented on src/main/java/webserver/entity/HttpCookie.java
> +        return "Set-Cookie: " + toCookieString() + "; Path=/";
추가로,, `Set-Cookie`항목에서 Path가 먼저 나오면 JSESSIONID가 제대로 안먹더라고요.. 일단 다음과 같이 JSESSIONID먼저 추가하고, 나중에 나머지 쿠키 항목들을 추가할 수 있도록 구성했습니다..
```java
builder.append(JSESSIONID_KEY).append(COOKIE_KEY_VALUE_DELIMITER).append(cookieData.get(JSESSIONID_KEY)).append("; ");
cookieData.forEach((key, value) -> {
    if (!key.equals(JSESSIONID_KEY)) {
        builder.append(key).append(COOKIE_KEY_VALUE_DELIMITER).append(value).append("; ");
    }
});
```

2024-04-17 08:43 UTC, BuchuKim commented on src/main/java/webserver/WebApplicationServer.java
> +    private static ControllerMapper createControllerMapper() {
이와 같이 구현해보았어요.
1. `ControllerMapper`의 필드로 `Map<HttpMethod, PathMapper>`를 두었습니다.
2. `PathMapper`의 필드로 `Map<String, Controller>`가 존재합니다.
3. 현재 `WebApplicationServer.java`에서, `ControllerMapper#add(HttpMethod method, Controller controller)`를 호출해 각 메소드에 맞는 컨트롤러를 추가할 수 있습니다. (이 때 컨트롤러의 `TARGET_PATHS`를 그대로 이용합니다)
4. 사용자 요청이 들어오면 `ControllerMapper#findControllerByRequest`를 호출하여, `RequestEntity`의 요청 메소드와 path에 맞는 Controller를 매핑할 수 있도록 했습니다.

2024-04-17 08:45 UTC, BuchuKim commented on src/main/java/webserver/WebApplicationServer.java
> +    private static ControllerMapper createControllerMapper() {
초기화 코드는 다소 더럽지만 아래와 같아요.. 🥹 (`WebApplicationServer.java`에서 확인 가능)
```java
private static ControllerMapper createControllerMapper() {
        UserService userService = new UserService();
        FileService fileService = new FileService();
        SessionManager sessionManager = new SessionManager(new HashMap<>());
        final UserCreateController userCreateController = new UserCreateController(userService);
        final LoginController loginController = new LoginController(userService, sessionManager);
        final LoginFormController loginFormController = new LoginFormController(fileService, sessionManager);
        final UserController userController = new UserController(userService, sessionManager);
        final FileController fileController = new FileController(fileService);

        ControllerMapper controllerMapper = new ControllerMapper();
        controllerMapper.addController(HttpMethod.GET, userCreateController);
        controllerMapper.addController(HttpMethod.POST, userCreateController);
        controllerMapper.addController(HttpMethod.GET, loginFormController);
        controllerMapper.addController(HttpMethod.POST, loginController);
        controllerMapper.addController(HttpMethod.GET, userController);
        controllerMapper.addController(HttpMethod.GET, fileController);
        return controllerMapper;
    }
```

2024-04-17 08:54 UTC, BuchuKim commented on README.md
```
HTTP와 관련된 것들 = 구현체(HTTP가 붙은 모든것)
비즈니스 로직 = 도메인 (HTTP가 아닌 다른 통신 프로토콜로 옮겨가도 변화가 없어야 함)
```
..가 제가 생각한 도메인과 구현체의 차이입니다.
때문에 현재 과제는 비즈니스 로직이 아니라 세부 기술(HTTP)을 다루고 있어서, 도메인 로직이 없다고 생각했습니다. 그래서 utils를 따로 뺀것 같아요😅
리뷰어님 말씀 들어보니 시스템에 따라 생각해야하는 비즈니스 로직의 범위를 잘 따져야겠다는 생각이 듭니다. 제가 utils에 두었던 Parser클래스들은 WAS에서 사용되는 요청/응답 객체를 만들기 위한 로직이 들어갔다고 볼 수 있겠네요. 좋은 설명 감사합니다~!~!

2024-04-17 08:55 UTC, BuchuKim commented on src/main/java/controller/ControllerMapper.java
> +    private final Map<String, Controller> controllers;
일단 제가 생각하기에 조금 더 직관적인 전자의 방법을 택했습니다. `Function` 함수형 인터페이스를 사용하는 것은 또 새로운 방법이네요! 현재의 방법도 단순히 `controllerMapper.find` 후 `controller.service`를 호출하면 끝이긴 하지만 메서드 참조를 사용하면 더 간단한 코드로 나타낼 수 있을 것 같습니다..

2024-04-17 12:31 UTC, seokhong approved these changes
승희님, 2단계 미션 코멘트 잘 반영하셨습니다. 👍 
2단계 PR 머지하겠습니다.
다음 단계 미션의 진행을 희망하시면 미션 진행 후 리뷰 요청 부탁드립니다.
이후 미션을 진행하지 않는 것으로 결정하신 경우, 남긴 코멘트에 대해서는 슬랙이나 2단계 미션의 PR에서 추가로 이야기 나눠도 좋으니 편하게 말씀 부탁드려요. 🙂

2024-04-17 12:31 UTC, seokhong commented on src/main/java/webserver/WebApplicationServer.java
> +        controllerMapper.addController(HttpMethod.GET, userCreateController);
사용자 등록 요청은 POST 로 변경되었으니, GET 요청을 처리하는 부분은 없어도 될 것으로 보이네요. :)

2024-04-17 12:31 UTC, seokhong commented on src/main/java/controller/LoginController.java
> +    private static final List<String> TARGET_PATHS = List.of("/user/login", "/user/login.html");
이 컨트롤러에서는 `/user/login`에 대한 요청만 처리할 것으로 보이고, `LoginFormController`에서 `/user/login.html` 요청을 처리할 것으로 보이네요!

2024-04-17 12:31 UTC, seokhong commented on src/main/java/webserver/entity/HttpCookie.java
> +    public static HttpCookie generateSessionIdCookie() {
쿠키의 입장에서 세션 아이디는 쿠키에 저장하는 여러 종류의 키/밸류 중 하나가 아닐까요? 세션 아이디 생성을 쿠키에게 하는 것이 적절할지 고민이 되네요.
`SessionEntity`를 생성할 때 스스로 키를 생성하도록 만드는 건 어떨까요?

2024-04-17 12:31 UTC, seokhong commented on src/main/java/webserver/entity/HttpCookie.java
> +        return "Set-Cookie: " + toCookieString() + "; Path=/";
구현하신 방법도 괜찮지만, `JSESSIONID_KEY`가 아닌 다른 키를 갖는 쿠키일 경우 동일한 이슈가 발생할 수 있을 것으로 보이네요.
> https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie

문서를 보면 다음과 같은 예시가 있는데요.
```
// Multiple attributes are also possible, for example:
Set-Cookie: <cookie-name>=<cookie-value>; Domain=<domain-value>; Secure; HttpOnly
```

이중 `<cookie-name>=<cookie-value>;` 부분은 쿠키를 사용하기 위한 필수 값이고, 이외의 값은 이 쿠키에 대한 속성으로 보입니다. 그렇다면 `name`, `value`는 별도의 필드로 관리하고, 이외의 값(e.g., `Path`)은 속성으로 관리하는 방법은 어떨까요? 코드에서 `key`를 비교하지 않고 더 단순하게 구현할 수 있을 것 같아요!

2024-04-17 12:31 UTC, merged