2단계 미션 제출합니다.
next-step/jwp-was-kakao pull request #33
Opened 2024-04-16 02:51 UTC by minleejae

## 변경사항

- 1단계 때 피드백 주셨던 내용 반영하여 디렉토리 구조를 변경하고, 리팩토링했습니다.
- HttpRequestHandler에 라우트 테이블을 추가하여 분기문을 사용하지 않도록 변경하였습니다.
- 로그인 기능을 구현하고, Session을 구현했습니다.

2024-04-17 02:18 UTC, hyunssooo requested changes
안녕하세요. 🙂
이번 step도 빠르게 구현해 주셨네요! 
몇 가지 코멘트 남겼어요. 확인 부탁드립니다!
함께 고민해 보고 싶은 부분은 코멘트나 DM 으로 남겨주세요!

2024-04-17 02:18 UTC, hyunssooo commented on src/main/java/http/request/RequestStartLine.java
> +    private final String url;
RequestStartLine 을 조금 더 명확하게 나눠볼 수 있지 않을까요? url도 객체로 만들어 질 수 있을 것 같아요. 
https://developer.mozilla.org/ko/docs/Web/HTTP/Messages#%EC%8B%9C%EC%9E%91_%EC%A4%84
참고해 보시면 좋을 것 같아요.

2024-04-17 02:18 UTC, hyunssooo commented on src/main/java/webserver/commands/GetUserLoginCommand.java
> +        if (cookies == null || !cookies.contains("JSESSIONID")) {
Cookie도 객체로 만들어 볼 수 있지 않을까요?

2024-04-17 02:18 UTC, hyunssooo commented on src/main/java/webserver/commands/GetUsersCommand.java
> +    }
이 코드는 반복되고 있네요. Redirect Response 가 필요한 경우 계속 코드를 작성하는 것이 좋을까요?

2024-04-17 02:18 UTC, hyunssooo commented on src/main/java/webserver/commands/CreateUserCommand.java
이 부분 제가 놓친 것 같은데요. 
User 중복 검증에 대한 비즈니스 로직도 구현되어야 하지 않을까요?

2024-04-17 02:18 UTC, hyunssooo commented on src/main/java/webserver/HttpRequestHandler.java
> +    }
key 값을 String으로 관리하기 보다 객체로 관리할 수 있지 않을까요? HttpMethod, endPoint 를 가지는 객체를 만들어 볼 수 있을 것 같아요.

2024-04-17 02:18 UTC, hyunssooo commented on src/main/java/webserver/HttpRequestHandler.java
> +        String specificKey = method + ":" + path;
상수화로 가독성을 높여보면 좋겠습니다. 전체적으로 하드코딩된 부분들은 확인해 보시면 좋을 것 같아요.

2024-04-17 02:18 UTC, hyunssooo commented on src/main/java/webserver/commands/GetUserLoginCommand.java
> +
이 부분은 꽤 자주 보이는데요. 정적 팩터리 메서드를 제공해도 괜찮을 것 같아요.

2024-04-17 02:18 UTC, hyunssooo commented on src/main/java/webserver/commands/GetUsersCommand.java
> +                    .collect(Collectors.toList());
꽤 복잡한거 같은데요. DTO로 만들어 보는 것은 어떨까요?

2024-04-17 02:18 UTC, hyunssooo commented on src/main/java/webserver/commands/GetUsersCommand.java
> +            Handlebars handlebars = new Handlebars(loader);
TemplateLoader, Handlebars 는 미리 만들어두고 재사용 가능하지 않을까요?

2024-04-17 06:28 UTC, minleejae commented on src/main/java/http/request/RequestStartLine.java
> +    private final String url;
url을 객체로 만들어 관리하도록 변경했습니다. [607eefb](https://github.com/next-step/jwp-was-kakao/pull/33/commits/607eefb9d51e910badf9fd16e1d4932e65ebf5a3)

2024-04-17 07:22 UTC, minleejae commented on src/main/java/webserver/commands/GetUserLoginCommand.java
> +
builder 패턴을 사용하면 더 확장성이 있을 것 같아 리팩토링 하였습니다. [fc3c41f](https://github.com/next-step/jwp-was-kakao/pull/33/commits/fc3c41f7b625a05dbf1020e7a577840170778f78)

2024-04-17 07:46 UTC, minleejae commented on src/main/java/webserver/commands/GetUsersCommand.java
> +    }
Redirect Response를 생성하는 메서드를 추가하여 이를 재사용하도록 개선했습니다. [961be8a](https://github.com/next-step/jwp-was-kakao/pull/33/commits/961be8a044e3f65eb7ef63bc6398b80f263646da)

2024-04-17 07:49 UTC, minleejae commented on src/main/java/webserver/commands/CreateUserCommand.java
유저 중복 검증을 추가했습니다. [212d438](https://github.com/next-step/jwp-was-kakao/pull/33/commits/212d43806119ec443276d029d994e4f170ea70ed)

2024-04-17 09:28 UTC, minleejae commented on src/main/java/webserver/commands/GetUserLoginCommand.java
> +        if (cookies == null || !cookies.contains("JSESSIONID")) {
cookie도 객체로 만들었습니다. [72a885e](https://github.com/next-step/jwp-was-kakao/pull/33/commits/72a885e3a295c65156bbb835280a66c55d4d6653)

2024-04-17 14:14 UTC, minleejae commented on src/main/java/webserver/HttpRequestHandler.java
> +    }
route Key를 객체로 관리하도록 변경했습니다. [fc7f4f0](https://github.com/next-step/jwp-was-kakao/pull/33/commits/fc7f4f02ab25566e64477deda1fea722077f135d)

2024-04-17 14:43 UTC, minleejae commented on src/main/java/webserver/commands/GetUsersCommand.java
> +                    .collect(Collectors.toList());
Dto를 만들었습니다. [e9319f9](https://github.com/next-step/jwp-was-kakao/pull/33/commits/e9319f9e058f76230b3e24d0c3a7a6218e232a11)

2024-04-18 15:25 UTC, hyunssooo approved these changes
안녕하세요.
미션 진행하신다고 고생 많으셨습니다.
몇 가지 가벼운 코멘트 남겼는데요. 시간 나시면 확인 부탁드려요! 
고생하셨습니다!

2024-04-18 15:25 UTC, hyunssooo commented on src/main/java/service/UserService.java
> +public class UserService {
구조상 command 객체들이 controller 역할을 하고 있는 걸로 보여요. 
UserService 에 static으로 제공 되지 않아도 괜찮을 것 같습니다. 
spring을 사용하면 framework가 쉽게 di를 해주지만 여기선 직접 해주시면 될 것 같아요. 

HttpRequestHandler static 에서 userService를 하나 생성해 각가 넣어주면 될 것 같습니다. :)

2024-04-18 15:25 UTC, hyunssooo commented on src/main/java/service/UserService.java
> +    }
이 부분도 user 객체에게 직접 물어볼 수 있지 않을까요? 자동차 경주와 로또 미션을 떠올려 객체에게 메시지를 보내보면 좋을 것 같습니다.

2024-04-18 15:25 UTC, hyunssooo commented on src/main/java/webserver/commands/GetUsersCommand.java
> +    }
```java
    private static final Handlebars handlebars;

    static {
        TemplateLoader loader = new ClassPathTemplateLoader("/templates", ".html");
        handlebars = new Handlebars(loader);
    }
```

이렇게도 가능하겠네요!

2024-04-18 15:25 UTC, hyunssooo commented on src/main/java/webserver/commands/HttpRequestCommand.java
> +public interface HttpRequestCommand {
현재는 같은 프로젝트이지만 framework 영역, 비즈니스 영역을 나눠 고민해 보시면 좋을 것 같습니다. 
HttpRequestCommand의 구현체들은 어떤 영역에 속할 수 있을까요? 
이 부분도 꼭 도전해 보시면 좋을 것 같습니다!

2024-04-18 15:25 UTC, merged